(function(global){
'use strict';
const KEY='libreecho-pages-demo-v2',started=Date.now();
const defaults=()=>({audio:{volume:64,microphone_gain:70,notification_volume:55,microphone_muted:false,startup_sound:true,amplifier_on:true,output_available:true},led:{colour:{r:72,g:216,b:118},brightness:72,boot_profile:{r:72,g:216,b:118,brightness:72},profiles:{listening:'#48b9ff',thinking:'#a873ef',error:'#ef5050',dnd:'#be2323'}},buttons:{short_press:'Start listening',long_press:'Open pairing mode',hardware_mute:true},wake:{enabled:true,wake_word:'LibreEcho',sensitivity:68,cooldown_ms:1500,model_status:'ready',detected_count:2,cpu_cost_percent:8,memory_cost_mb:34,local_processing:true},network:{state:'connected',ssid:'LibreNet-5G',signal:82,ip:'192.0.2.42',gateway:'192.0.2.1',dns:'192.0.2.1',hostname:'libreecho-dev',internet:true,dhcp:true,ssh:false,api_lan:false},privacy:{local_only:true,audio_retention:'none',diagnostic_telemetry:false,log_retention_hours:24,crash_reports:false},integrations:[{id:'home-assistant',name:'Home Assistant',enabled:false},{id:'mqtt',name:'MQTT',enabled:false},{id:'rest',name:'Local REST API',enabled:true},{id:'bluetooth',name:'Bluetooth audio',enabled:false}],deviceState:'online',logs:[{timestamp:Math.floor(Date.now()/1000)-42,level:'info',message:'Browser demo backend initialized'},{timestamp:Math.floor(Date.now()/1000)-18,level:'info',message:'Mock Wi-Fi link is connected'}],failNext:''});
let state;
try{state=Object.assign(defaults(),JSON.parse(localStorage.getItem(KEY)||'{}'))}catch(_){state=defaults()}
state.ota=Object.assign({supported:false,channel:'development',current_slot:'n/a',inactive_slot:'n/a',state:'development',progress:0,rollback_available:false,rollback_version:'',automatic_updates:false,latest_version:'',installed_version:'LibreEcho OS PRD development',check_status:'not-checked',source_reachable:'unknown',source:'not configured',last_check_epoch:0,last_success_epoch:0,pending_reboot:false,pending_version:'',max_upload_bytes:33554432},state.ota||{})
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function clone(value){return JSON.parse(JSON.stringify(value))}
function body(opt){if(!opt||opt.body==null)return{};if(typeof opt.body==='object')return opt.body;try{return JSON.parse(opt.body)}catch(_){throw new Error('Request body is not valid JSON')}}
function log(message,level='info'){state.logs.push({timestamp:Math.floor(Date.now()/1000),level,message});state.logs=state.logs.slice(-128);save()}
function number(value,min,max,name){if(typeof value!=='number'||value<min||value>max)throw new Error(`${name} must be between ${min} and ${max}`);return value}
function exported(){let mask=0;state.integrations.forEach((x,i)=>{if(x.enabled)mask|=1<<i});return{schema_version:1,volume:state.audio.volume,microphone_gain:state.audio.microphone_gain,microphone_muted:state.audio.microphone_muted,led_r:state.led.colour.r,led_g:state.led.colour.g,led_b:state.led.colour.b,led_brightness:state.led.brightness,wake_word:state.wake.wake_word,wake_sensitivity:state.wake.sensitivity,hostname:state.network.hostname,ssh:state.network.ssh,api_lan:state.network.api_lan,button_short:state.buttons.short_press,button_long:state.buttons.long_press,privacy_local_only:state.privacy.local_only,privacy_audio_retention:state.privacy.audio_retention!=='none',privacy_telemetry:state.privacy.diagnostic_telemetry,privacy_crash_reports:state.privacy.crash_reports,privacy_log_hours:state.privacy.log_retention_hours,integrations:mask}}
function restore(x){const required=['schema_version','volume','microphone_gain','microphone_muted','led_r','led_g','led_b','led_brightness','wake_word','wake_sensitivity','hostname','ssh','api_lan','button_short','button_long','privacy_local_only','privacy_audio_retention','privacy_telemetry','privacy_crash_reports','privacy_log_hours','integrations'];if(!x||x.schema_version!==1||required.some(k=>!(k in x)))throw new Error('Configuration file is invalid or incomplete');number(x.volume,0,100,'Volume');number(x.microphone_gain,0,100,'Microphone gain');number(x.led_r,0,255,'LED red');number(x.led_g,0,255,'LED green');number(x.led_b,0,255,'LED blue');number(x.led_brightness,0,100,'LED brightness');state.audio.volume=x.volume;state.audio.microphone_gain=x.microphone_gain;state.audio.microphone_muted=!!x.microphone_muted;state.led.colour={r:x.led_r,g:x.led_g,b:x.led_b};state.led.brightness=x.led_brightness;state.wake.wake_word=String(x.wake_word).slice(0,63);state.wake.sensitivity=number(x.wake_sensitivity,0,100,'Sensitivity');state.network.hostname=String(x.hostname).slice(0,63);state.network.ssh=!!x.ssh;state.network.api_lan=!!x.api_lan;state.buttons.short_press=String(x.button_short).slice(0,31);state.buttons.long_press=String(x.button_long).slice(0,31);state.privacy={local_only:!!x.privacy_local_only,audio_retention:x.privacy_audio_retention?'24h':'none',diagnostic_telemetry:!!x.privacy_telemetry,crash_reports:!!x.privacy_crash_reports,log_retention_hours:x.privacy_log_hours};state.integrations.forEach((item,i)=>item.enabled=!!(x.integrations&(1<<i)));log('Configuration restored from uploaded JSON','warning')}
async function request(path,opt={}){await new Promise(resolve=>setTimeout(resolve,90));const method=(opt.method||'GET').toUpperCase(),data=body(opt);path=path.replace(/^\/api\/v1/,'')||'/';
if(path==='/'&&method==='GET')return{name:'LibreEcho API',version:'v1',status:'/api/v1/status',openapi:'openapi.json',swagger:'swagger.html',demo:true};
if(path==='/config'&&method==='GET')return{api_version:1,csrf_token:'libreecho-local',authentication:'development-disabled',bind_policy:'static-browser-demo',max_request_body:16384};
if(path==='/config/export'&&method==='GET')return exported();
if(path==='/config/import'&&method==='POST'){restore(data);return{restored:true,schema_version:1}}
if(path==='/status'&&method==='GET'){const tick=Math.floor((Date.now()-started)/5000),cpu=19+(tick*7%13),mem=45+(tick%4),temperature=47+((tick*3)%7)-3;return{backend:'mock',simulated:true,uptime_seconds:86400*3+Math.floor((Date.now()-started)/1000),cpu_percent:cpu,memory_percent:mem,memory_used_mb:Math.round(512*mem/100),memory_total_mb:512,storage_available:true,storage_percent:19,storage_used_mb:778,storage_total_mb:4096,cpus:[0,1,2,3].map(id=>({id,online:true,frequency_khz:1300000,utilization_percent:Math.max(4,cpu-id*3)})),temperature_c:temperature,device_state:state.deviceState}}
if(path==='/device'&&method==='GET')return{name:'LibreEcho demo device',hostname:state.network.hostname,model:'Amazon Echo (2nd generation)',serial:'demo',os_version:'LibreEcho OS PRD development',kernel:'Linux 6.1.178 (LibreEcho PRD)',hardware_revision:'Development simulation',backend:'mock'};
if(path==='/audio'){if(method==='PUT'){if('volume'in data)state.audio.volume=number(data.volume,0,100,'Volume');if('microphone_gain'in data)state.audio.microphone_gain=number(data.microphone_gain,0,100,'Microphone gain');if('microphone_muted'in data)state.audio.microphone_muted=!!data.microphone_muted;log('Audio settings updated')}save();return clone(state.audio)}
if(path==='/audio/test'&&method==='POST'){log('Simulated test tone played');return{playing:true}}
if(path==='/led'){if(method==='PUT'){if(['r','g','b'].every(k=>k in data))state.led.colour={r:number(data.r,0,255,'Red'),g:number(data.g,0,255,'Green'),b:number(data.b,0,255,'Blue')};if('brightness'in data)state.led.brightness=number(data.brightness,0,100,'Brightness');log('LED settings updated')}save();return clone(state.led)}
if(path==='/led/test'&&method==='POST'){log('Simulated LED test started');return{testing:true}}
if(path==='/buttons'){if(method==='PUT')Object.assign(state.buttons,data);save();return clone(state.buttons)}
if(path==='/wake-word'){if(method==='PUT'){if(data.wake_word)state.wake.wake_word=String(data.wake_word).slice(0,63);if('sensitivity'in data)state.wake.sensitivity=number(data.sensitivity,0,100,'Sensitivity');log('Wake-word settings updated')}save();return clone(state.wake)}
if(path==='/wake-word/test'&&method==='POST'){state.wake.detected_count++;log(`Wake word '${state.wake.wake_word}' detected`);return{detected:true}}
if(path==='/network'){if(method==='PUT'){if('hostname'in data&&!/^[a-zA-Z0-9][a-zA-Z0-9.-]{0,62}$/.test(data.hostname))throw new Error('Hostname contains invalid characters');Object.assign(state.network,data);log('Network settings updated')}save();return clone(state.network)}
if(path==='/network/wifi/scan'&&method==='GET'){if(state.failNext==='wifi-scan'){state.failNext='';save();throw new Error('Simulated Wi-Fi scan failure')}return{networks:[{ssid:'LibreNet-5G',security:'wpa2',signal:88},{ssid:'LibreNet-IoT',security:'wpa2',signal:71},{ssid:'Neighbourhood WiFi',security:'wpa3',signal:54},{ssid:'Open Test Network',security:'open',signal:37}]}}
if(path==='/network/wifi/connect'&&method==='POST'){if(!data.ssid)throw new Error('SSID is required');state.network={...state.network,state:'connecting',ssid:data.ssid,signal:0,internet:false,ip:''};save();log(`Connecting to ${data.ssid}`);setTimeout(()=>{state.network={...state.network,state:'connected',signal:76,internet:true,ip:'192.0.2.43'};log(`Connected to ${data.ssid}`)},1200);return{state:'connecting'}}
if(path==='/network/wifi/disconnect'&&method==='POST'){Object.assign(state.network,{state:'disconnected',ssid:'',signal:0,internet:false,ip:''});log('Wi-Fi disconnected');return{state:'disconnected'}}
if(path==='/privacy'){if(method==='PUT'){Object.assign(state.privacy,data);log('Privacy settings updated')}save();return clone(state.privacy)}
if(path==='/integrations'&&method==='GET')return{items:clone(state.integrations)};
if(path.startsWith('/integrations/')&&method==='PUT'){const id=decodeURIComponent(path.slice(14)),item=state.integrations.find(x=>x.id===id);if(!item)throw new Error('Integration was not found');item.enabled=!!data.enabled;log(`${item.name} ${item.enabled?'enabled':'disabled'}`);return{items:clone(state.integrations)}}
if(path==='/playback'&&method==='GET')return{state:'idle',source:null,metadata:{available:false}};
if(path==='/system'&&method==='GET')return{update_channel:'development',timezone:'Europe/London',ntp:true,ntp_state:'synchronized',clock_source:'ntp',rtc_available:true,rtc_persisted:true,ntp_servers:'time.cloudflare.com,time.nist.gov'};
if(path==='/system/update'&&method==='GET')return clone(state.ota);
if(path==='/system/update/check'&&method==='POST'){if(!state.ota.supported)throw new Error('Signed updates are unavailable in the browser demo');const now=Math.floor(Date.now()/1000);state.ota.last_check_epoch=now;state.ota.last_success_epoch=now;state.ota.check_status='update-available';state.ota.source_reachable='true';save();return clone(state.ota)}
if(path==='/system/update/automatic'&&method==='PUT'){if(!state.ota.supported)throw new Error('Signed updates are unavailable in the browser demo');state.ota.automatic_updates=!!data.enabled;save();return clone(state.ota)}
if(path==='/system/update/apply'&&method==='POST'){if(!state.ota.supported)throw new Error('Signed updates are unavailable in the browser demo');state.ota.state='installed';state.ota.current_slot=state.ota.inactive_slot;state.ota.inactive_slot=state.ota.current_slot==='A'?'B':'A';state.ota.installed_version=state.ota.latest_version;state.ota.check_status='up-to-date';state.ota.pending_reboot=false;save();return clone(state.ota)}
if(['/system/reboot','/system/shutdown','/system/factory-reset'].includes(path)&&method==='POST'){const action=path.split('/').pop();state.deviceState=action==='shutdown'?'shutting-down':'restarting';log(`Simulated ${action} requested`,'warning');setTimeout(()=>{if(action==='factory-reset'){state=defaults();save()}else{state.deviceState='online';save()}},1400);save();return{accepted:true}}
if(path==='/logs'&&method==='GET'||path==='/logs/stream'&&method==='GET')return{entries:clone(state.logs),bounded:true,capacity:128};
if(path==='/diagnostics'&&method==='GET')return{checks:[{name:'configuration',status:'ok'},{name:'browser mock backend',status:'ok'},{name:'hardware adapters',status:'development'}]};
if(path==='/diagnostics/export'&&method==='POST')return{filename:'libreecho-diagnostics.json',redacted:true};
if(path==='/dev/mock'&&method==='POST'){if(data.action==='fail-next')state.failNext=data.value;if(data.action==='set-temperature')state.temperature=Number(data.value);save();return{applied:true}}
throw new Error(`Endpoint not found: ${method} /api/v1${path}`)}
function reset(){localStorage.removeItem(KEY);state=defaults()}
global.LibreEchoDemo={request,reset,exportConfiguration:exported};
})(window);
